meta:
  name: 失落之地
  version: "0.103"

time:
  start_turn: 4
  end_turn: 500
  display_era_year: 2056
  turns_per_year: 12

stat:
  min: 0
  stability_max: 50
  relation_max: 100

player:
  id: player
  name: ""
  short_name: ""
  leader: ""

server:
  host: 127.0.0.1
  port: 8010
